from . import hr_hospital_mass_reassign_doctor_wizard
from . import hr_hospital_disease_report_wizard
from . import hr_hospital_reschedule_visit_wizard
from . import hr_hospital_doctor_schedule_wizard
from . import hr_hospital_patient_card_export_wizard
